services:
  qdrant:
    image: qdrant/qdrant:v1.16.3
    container_name: findme_qdrant
    restart: always
    ports:
      - "6334:6334"
      - "6333:6333"
    volumes:
      - qdrant:/qdrant/storage
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/127.0.0.1/6333 && echo -e 'GET /readyz HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && grep -q 'HTTP/1.1 200' <&3"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - findme_emb_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: findme_emb
    restart: always
    environment:
      - OLLAMA_EMBEDDING_HOST=${OLLAMA_EMBEDDING_HOST}
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT}
    ports:
      - "8000:8000"
    depends_on:
      qdrant:
        condition: service_healthy
    networks:
      - findme_emb_network

networks:
  findme_emb_network:
    driver: bridge

volumes:
  qdrant:

