services:
  db:
    image: qdrant/qdrant:1.16.3
    restart: unless-stopped
    container_name: findme_qdrant
    ports:
      - "6334:6334"
    volumes:
      - qdrant:/qdrant/storage
    network:
      - findme_emb_network

  ollama:
    image: ollama/ollama:latest
    container_name: findme_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - findme_emb_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: findme_emb
    depends_on:
      - db
      - ollama
    network:
      - findme_emb_network

network:
  findme_emb_network:
    driver: bridge

volumes:
  qdrant:
  ollama:
